version: "3.4"
services:
  prom:
    image: prom/prometheus:latest
    ports:
      - 80:9090
    volumes:
      - ./prom/prometheus.yml:/etc/prometheus/prometheus.yml

  animal-name-service:
    build: animal-name-service

  scientist-name-service:
    build: scientist-name-service

  name-generator-service:
    build: name-generator-service
    ports:
      - 82:8080

  jaeger:
    image: jaegertracing/all-in-one:1.17
    ports:
      - 81:16686
    depends_on:
      - prom
